spring:
  application:
    name: discovery

server:
  port: 8761

eureka:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://discovery:${server.port}/eureka/

