server:
  port: 10000

sidecar:
  port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: info
    me.jefferlau: debug

zuul:
  routes:
    user:
      # 请求后方服务时带上 Authorization 头信息
      # sensitiveHeaders:
      path: /user/**
      stripPrefix: true
