server:
  port: 9006

logging:
  level:
    ROOT: info
    me.jefferlau: debug
  file: logs/${spring.application.name}.log

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true

